console.log(Math.ceil(2.1));
console.log(Math.ceil(2.6));
console.log("---------------------------");
console.log(Math.floor(2.1));
console.log(Math.floor(2.6));
console.log("---------------------------");
console.log(Math.round(2.1));
console.log(Math.round(2.6));
console.log("---------------------------");
console.log(Math.abs(5));
console.log(Math.abs(-5));
console.log("---------------------------");
console.log(Math.trunc(5.2356684657));
console.log("---------------------------");
console.log(Math.pow(5,2));          //5^2
console.log("---------------------------");
console.log(Math.sqrt(5));
console.log(Math.sqrt(25));
console.log("---------------------------");
console.log(Math.cbrt(5));
console.log(Math.cbrt(25));
console.log("---------------------------");
console.log(Math.max(5,4,6,8,2,10));
console.log(Math.min(5,4,6,8,2,10));
console.log("---------------------------");
console.log(Math.random());
console.log("---------------------------");
console.log((2135.2456687654).toFixed(2))
